# Generated by Django 3.1.5 on 2021-01-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210118_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderprofile',
            old_name='age',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='age',
            new_name='birthday',
        ),
    ]
