# Generated by Django 3.1.5 on 2021-01-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
