# Generated by Django 3.1.5 on 2021-02-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
        ('users', '0009_auto_20210208_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cources',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cources.courses'),
        ),
    ]
