# Generated by Django 3.1.5 on 2021-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
        ('users', '0010_teacher_cources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='cources',
        ),
        migrations.AddField(
            model_name='teacher',
            name='cources',
            field=models.ManyToManyField(to='cources.Courses'),
        ),
    ]
