# Generated by Django 3.1.5 on 2021-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='finish',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.TimeField(),
        ),
    ]
